name: Build

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        description: The Java version to set up. See https://github.com/actions/setup-java/blob/v4/action.yml#L6
        default: '21'
      runs-on:
        type: string
        description: the image on which to run the job
        default: ubuntu-latest
      enable-docker-for-windows:
        type: boolean
        description: Install & start Docker on a Windows runner
        default: false
    secrets:
      GH_TOKEN_REPO:
        description: Token to access private repositories of the lernejo org
        required: true
      CODECOV_TOKEN:
        description: Repository Codecov token. See https://github.com/codecov/codecov-action/blob/v4/action.yml#L5
        required: true
      KOREKTO_VAULT_KEY:
        description: AES B64 key to decode Korekto-Vault files
        required: false

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven

      - name: Debug JDK info
        shell: bash
        run: |
          java -Xmx4M -XX:+PrintCommandLineFlags -version
          ./mvnw -version
          echo $JAVA_HOME

      - name: Install & start Docker for Windows
        if: ${{ contains(inputs.runs-on, 'windows') && inputs.enable-docker-for-windows }}
        uses: crazy-max/ghaction-setup-docker@a37e5b7d617b6fa0ee22a6adad6077dbed458a49 # latest master 25/11/2024
        with:
          rootless: true
          set-host: true
          context: docker_engine

      - name: Run tests (linux)
        shell: bash
        if: ${{ contains(inputs.runs-on, 'ubuntu') }}
        run: ./mvnw -U test -Dgithub_token="$GH_TOKEN_REPO" -DfailIfNoTests -Dkorekto_vault_key="$KOREKTO_VAULT_KEY"
        env:
          GH_TOKEN_REPO: ${{ secrets.GH_TOKEN_REPO }}
          KOREKTO_VAULT_KEY: ${{ secrets.KOREKTO_VAULT_KEY }}

      - name: Run tests (windows)
        shell: pwsh
        if: ${{ contains(inputs.runs-on, 'windows') }}
        run: .\mvnw.cmd -U test -Dgithub_token="$env:GH_TOKEN_REPO" -DfailIfNoTests -Dkorekto_vault_key="$env:KOREKTO_VAULT_KEY"
        env:
          GH_TOKEN_REPO: ${{ secrets.GH_TOKEN_REPO }}
          KOREKTO_VAULT_KEY: ${{ secrets.KOREKTO_VAULT_KEY }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ always() && contains(inputs.runs-on, 'ubuntu') && github.actor != 'dependabot[bot]' }}
        with:
          files: |
            target/surefire-reports/*.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: ${{ always() && contains(inputs.runs-on, 'windows') && github.actor != 'dependabot[bot]' }}
        with:
          files: |
            target/surefire-reports/*.xml

      - uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ env.CODECOV_TOKEN != '' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
